# Generated by Django 4.0 on 2022-05-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employe', '0007_remove_employe_indemnite_employe_identreprise'),
        ('Indemnites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indemnites',
            name='employe',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employe.employe'),
        ),
    ]
