# Generated by Django 4.0.3 on 2022-06-24 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employe', '0002_remove_employe_indemnite_remove_employe_prime'),
        ('Indemnites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indemnites',
            name='employe',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employe.employe'),
        ),
        migrations.AddField(
            model_name='indemnites',
            name='type',
            field=models.CharField(choices=[('Valeur fixe', 'Valeur fixe'), ('pourcentage sur salaire', 'pourcentage sur salaire')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='indemnites',
            name='valeur',
            field=models.FloatField(default=0, null=True),
        ),
    ]
