# Generated by Django 4.0 on 2022-06-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indemnites', '0002_indemnites_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='indemnites',
            name='valeurenpourcentage',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='indemnites',
            name='valeurfixe',
            field=models.FloatField(default=0, null=True),
        ),
    ]
