# Generated by Django 4.0 on 2022-06-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indemnites', '0003_indemnites_valeurenpourcentage_indemnites_valeurfixe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indemnites',
            name='valeurenpourcentage',
        ),
        migrations.RemoveField(
            model_name='indemnites',
            name='valeurfixe',
        ),
        migrations.AddField(
            model_name='indemnites',
            name='type',
            field=models.CharField(choices=[('Valeur fixe', 'Valeur fixe'), ('pourcentage sur salaire', 'pourcentage sur salaire')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='indemnites',
            name='valeur',
            field=models.FloatField(default=0, null=True),
        ),
    ]
