# Generated by Django 4.0.3 on 2022-06-24 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='indemnite',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='prime',
        ),
    ]
