# Generated by Django 4.0.3 on 2022-06-03 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Employe.employe')),
            ],
        ),
    ]
