# Generated by Django 4.0.3 on 2022-06-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(blank=True, choices=[('Retirée', 'Retirée'), ('Pas retirée', 'Pas retirée')], max_length=50, null=True)),
                ('typePrime', models.CharField(max_length=50, null=True)),
                ('valeur', models.IntegerField(null=True)),
            ],
        ),
    ]
