# Generated by Django 4.0.3 on 2022-06-03 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Entreprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeAdresse', models.CharField(choices=[('Adresse mail', 'Adresse mail'), ('Téléphone', 'Téléphone'), ('Site Internet', 'Site Internet'), ('Boite postale', 'Boite postale'), ('Pays', 'Pays'), ('Ville', 'Ville'), ('Quartier', 'Quartier'), ('Inplantation', 'Inplantation'), ('Fax', 'Fax')], max_length=50, null=True)),
                ('valeur', models.CharField(max_length=50, null=True)),
                ('entreprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Entreprise.entreprise')),
            ],
        ),
    ]
